version: '2'
services:
  todoapp:
    container_name: todoapp
    restart: always
    build: .
    environment:
      - ROOKOUT_AGENT_HOST=rookout-agent
    ports:
      - "4000:4000"
    links:
      - rookout-agent
  rookout-agent:
    container_name: rookout-agent
    image: rookout/agent
    environment:
      - ROOKOUT_TOKEN=9458bd3761922d3b8d15ff4c469580a1aa8bc79ccd06ef99f5c783eebb259049
    ports:
      - "7486:7486"
