version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    links:
      - mongo
  web:
    container_name: web
    restart: always
    build: ./web
    ports:
      - "5000:5000"
    links:
      - api